version: '3'

services:
   db:
    image: postgres
    environment:
      - POSTGRES_DB=leoclimb
      - POSTGRES_USER=paul
      - POSTGRES_PASSWORD=santamaria
   web:
    build: .
    ports:
      - "8000:8000"
    container_name: app-leoclimb
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db