version: '3'

services:
   db:
    image: postgres
    restart: always
    container_name: db-leoclimb
    environment:
      - POSTGRES_DB=leoclimb
      - POSTGRES_USER=paul
      - POSTGRES_PASSWORD=paultapedes7a
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db-export:/home/db-export
    ports: 
      - 5432:5432
   web:
    build: .
    tty: true
    ports:
      - "9000:8000"
    container_name: app-leoclimb
    command: bash -c "yes yes | bin/python3 manage.py collectstatic"
    command: bash -c "bin/python3 app/manage.py migrate"
    command: bash -c "cd app/ && ../bin/gunicorn siteLeoClimb.wsgi:application --bind=0.0.0.0:8000"
    depends_on:
      - db
    links:
      - db:db
volumes:
  data:
  db-export: