version: '3'

services:
   db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=leoclimb
      - POSTGRES_USER=paul
      - POSTGRES_PASSWORD=paultapedes7a
    volumes:
      - ./data:/var/lib/postgresql/data
    ports: 
      - 5000:5432
   web:
    build: .
    ports:
      - "9000:8000"
    container_name: app-leoclimb
    restart: always
#    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: gunicorn siteLeoClimb.wsgi:application --bind=0.0.0.0:8000
    depends_on:
      - db
    links:
      - db:db
volumes:
  data: