# Generated by Django 3.1.1 on 2020-12-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0002_bureau_membre_palmares_partenaire_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('image', models.FileField(blank=True, null=True, upload_to='palmares/')),
                ('menbre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appLeoClimb.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
