# Generated by Django 3.1.1 on 2020-12-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0005_auto_20201226_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
