# Generated by Django 3.1.1 on 2020-12-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0006_partenaire_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='partenaires/'),
        ),
    ]
