# Generated by Django 3.1.1 on 2020-12-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0007_auto_20201226_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevinciClimbingContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('date', models.DateField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ecole', models.CharField(max_length=100)),
                ('tshirt', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
