# Generated by Django 3.1.1 on 2020-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0008_devinciclimbingcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ecole', models.CharField(max_length=100)),
                ('tshirt', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='devinciclimbingcontest',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='devinciclimbingcontest',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='devinciclimbingcontest',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='devinciclimbingcontest',
            name='question',
        ),
        migrations.RemoveField(
            model_name='devinciclimbingcontest',
            name='tshirt',
        ),
        migrations.AlterField(
            model_name='devinciclimbingcontest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
