# Generated by Django 3.1.1 on 2020-12-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0010_galerie_galerieimage_merchandising_merchandisingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisingimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='merchandising/'),
        ),
        migrations.AlterField(
            model_name='galerieimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='galerie/'),
        ),
    ]
