# Generated by Django 3.1.1 on 2020-12-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0011_auto_20201229_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandisingimage',
            old_name='Merchandising',
            new_name='merchandising',
        ),
    ]
