# Generated by Django 3.1.1 on 2021-01-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0013_auto_20210103_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main',
            field=models.TextField(),
        ),
    ]
