# Generated by Django 3.1.1 on 2021-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0014_auto_20210113_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='place',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='poste',
            field=models.CharField(max_length=50),
        ),
    ]
