# Generated by Django 3.1.1 on 2021-01-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0015_auto_20210113_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='place',
            field=models.FloatField(default=0, unique=True),
        ),
    ]
