# Generated by Django 3.1.1 on 2021-01-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0017_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Accueil',
        ),
    ]
