# Generated by Django 3.1.1 on 2021-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0018_auto_20210126_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bureau',
            old_name='place',
            new_name='ordre',
        ),
        migrations.AddField(
            model_name='galerie',
            name='ordre',
            field=models.FloatField(default=None, null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palmare',
            name='ordre',
            field=models.FloatField(default=None, null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partenaire',
            name='ordre',
            field=models.FloatField(default=None, null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='accueil',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
