# Generated by Django 3.1.1 on 2021-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLeoClimb', '0019_auto_20210324_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='ordre',
            field=models.FloatField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='accueil',
            field=models.BooleanField(null=True),
        ),
    ]
